/* ============================================================
   DUOC UC
   MODELAMIENTO DE BASES DE DATOS
   SEMANA 7

   Caso: Holding Carpenter SPA
   Usuario: PRY2204_S7

   Actividad:
   Realizando el poblamiento y consultas en la base de datos
   con sentencias SQL
   ============================================================ */


/* ============================================================
   CASO 1
   IMPLEMENTACION DEL MODELO RELACIONAL
   ============================================================ */


/* ============================================================
   1. REGION
   ID inicia en 7 y aumenta de 2 en 2 mediante IDENTITY
   ============================================================ */

CREATE TABLE REGION (
    ID_REGION NUMBER(2)
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 7 INCREMENT BY 2),
    NOMBRE_REGION VARCHAR2(25) NOT NULL
);

ALTER TABLE REGION
    ADD CONSTRAINT REGION_PK
    PRIMARY KEY (ID_REGION);


/* ============================================================
   2. COMUNA
   PK compuesta: ID_COMUNA + COD_REGION
   ============================================================ */

CREATE TABLE COMUNA (
    ID_COMUNA     NUMBER(5) NOT NULL,
    COMUNA_NOMBRE VARCHAR2(25) NOT NULL,
    COD_REGION    NUMBER(2) NOT NULL
);

ALTER TABLE COMUNA
    ADD CONSTRAINT COMUNA_PK
    PRIMARY KEY (ID_COMUNA, COD_REGION);

ALTER TABLE COMUNA
    ADD CONSTRAINT COMUNA_REGION_FK
    FOREIGN KEY (COD_REGION)
    REFERENCES REGION(ID_REGION);


/* ============================================================
   3. GENERO
   ============================================================ */

CREATE TABLE GENERO (
    ID_GENERO          VARCHAR2(2) NOT NULL,
    DESCRIPCION_GENERO VARCHAR2(25) NOT NULL
);

ALTER TABLE GENERO
    ADD CONSTRAINT GENERO_PK
    PRIMARY KEY (ID_GENERO);


/* ============================================================
   4. ESTADO_CIVIL
   ============================================================ */

CREATE TABLE ESTADO_CIVIL (
    ID_ESTADO_CIVIL          VARCHAR2(2) NOT NULL,
    DESCRIPCION_EST_CIVIL    VARCHAR2(25) NOT NULL
);

ALTER TABLE ESTADO_CIVIL
    ADD CONSTRAINT ESTADO_CIVIL_PK
    PRIMARY KEY (ID_ESTADO_CIVIL);


/* ============================================================
   5. TITULO
   ============================================================ */

CREATE TABLE TITULO (
    ID_TITULO          VARCHAR2(3) NOT NULL,
    DESCRIPCION_TITULO VARCHAR2(60) NOT NULL
);

ALTER TABLE TITULO
    ADD CONSTRAINT TITULO_PK
    PRIMARY KEY (ID_TITULO);


/* ============================================================
   6. IDIOMA
   ID inicia en 25 y aumenta de 3 en 3 mediante IDENTITY
   ============================================================ */

CREATE TABLE IDIOMA (
    ID_IDIOMA NUMBER(3)
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 25 INCREMENT BY 3),
    NOMBRE_IDIOMA VARCHAR2(80) NOT NULL
);

ALTER TABLE IDIOMA
    ADD CONSTRAINT IDIOMA_PK
    PRIMARY KEY (ID_IDIOMA);


/* ============================================================
   7. COMPANIA
   ============================================================ */

CREATE TABLE COMPANIA (
    ID_EMPRESA      NUMBER(2) NOT NULL,
    NOMBRE_EMPRESA  VARCHAR2(25) NOT NULL,
    CALLE           VARCHAR2(50) NOT NULL,
    NUMERACION      NUMBER(5) NOT NULL,
    RENTA_PROMEDIO  NUMBER(8) NOT NULL,
    PCT_AUMENTO     NUMBER(4,3),
    COD_COMUNA      NUMBER(5) NOT NULL,
    COD_REGION      NUMBER(2) NOT NULL
);

ALTER TABLE COMPANIA
    ADD CONSTRAINT COMPANIA_PK
    PRIMARY KEY (ID_EMPRESA);

ALTER TABLE COMPANIA
    ADD CONSTRAINT COMPANIA_NOMBRE_UN
    UNIQUE (NOMBRE_EMPRESA);

ALTER TABLE COMPANIA
    ADD CONSTRAINT COMPANIA_COMUNA_FK
    FOREIGN KEY (COD_COMUNA, COD_REGION)
    REFERENCES COMUNA(ID_COMUNA, COD_REGION);


/* ============================================================
   8. PERSONAL
   ============================================================ */

CREATE TABLE PERSONAL (
    RUT_PERSONA        NUMBER(8) NOT NULL,
    DV_PERSONA         CHAR(1) NOT NULL,
    PRIMER_NOMBRE      VARCHAR2(25) NOT NULL,
    SEGUNDO_NOMBRE     VARCHAR2(25),
    PRIMER_APELLIDO    VARCHAR2(25) NOT NULL,
    SEGUNDO_APELLIDO   VARCHAR2(25),
    FECHA_CONTRATACION DATE NOT NULL,
    FECHA_NACIMIENTO   DATE NOT NULL,
    EMAIL              VARCHAR2(100),
    CALLE              VARCHAR2(50) NOT NULL,
    NUMERACION         NUMBER(5) NOT NULL,
    SUELDO             NUMBER(8) NOT NULL,
    COD_COMUNA         NUMBER(5) NOT NULL,
    COD_REGION         NUMBER(2) NOT NULL,
    COD_GENERO         VARCHAR2(2) NOT NULL,
    COD_ESTADO_CIVIL   VARCHAR2(2) NOT NULL,
    COD_EMPRESA        NUMBER(2) NOT NULL,
    ENCARGADO_RUT      NUMBER(8)
);

ALTER TABLE PERSONAL
    ADD CONSTRAINT PERSONAL_PK
    PRIMARY KEY (RUT_PERSONA);

ALTER TABLE PERSONAL
    ADD CONSTRAINT PERSONAL_COMPANIA_FK
    FOREIGN KEY (COD_EMPRESA)
    REFERENCES COMPANIA(ID_EMPRESA);

ALTER TABLE PERSONAL
    ADD CONSTRAINT PERSONAL_COMUNA_FK
    FOREIGN KEY (COD_COMUNA, COD_REGION)
    REFERENCES COMUNA(ID_COMUNA, COD_REGION);

ALTER TABLE PERSONAL
    ADD CONSTRAINT PERSONAL_GENERO_FK
    FOREIGN KEY (COD_GENERO)
    REFERENCES GENERO(ID_GENERO);

ALTER TABLE PERSONAL
    ADD CONSTRAINT PERSONAL_ESTCIVIL_FK
    FOREIGN KEY (COD_ESTADO_CIVIL)
    REFERENCES ESTADO_CIVIL(ID_ESTADO_CIVIL);

ALTER TABLE PERSONAL
    ADD CONSTRAINT PERSONAL_ENCARGADO_FK
    FOREIGN KEY (ENCARGADO_RUT)
    REFERENCES PERSONAL(RUT_PERSONA);


/* ============================================================
   9. TITULACION
   ============================================================ */

CREATE TABLE TITULACION (
    COD_TITULO   VARCHAR2(3) NOT NULL,
    PERSONA_RUT  NUMBER(8) NOT NULL,
    FECHA_TITULACION DATE NOT NULL
);

ALTER TABLE TITULACION
    ADD CONSTRAINT TITULACION_PK
    PRIMARY KEY (COD_TITULO, PERSONA_RUT);

ALTER TABLE TITULACION
    ADD CONSTRAINT TITULACION_PERSONAL_FK
    FOREIGN KEY (PERSONA_RUT)
    REFERENCES PERSONAL(RUT_PERSONA);

ALTER TABLE TITULACION
    ADD CONSTRAINT TITULACION_TITULO_FK
    FOREIGN KEY (COD_TITULO)
    REFERENCES TITULO(ID_TITULO);


/* ============================================================
   10. DOMINIO
   Relacion entre PERSONAL e IDIOMA
   ============================================================ */

CREATE TABLE DOMINIO (
    ID_IDIOMA   NUMBER(3) NOT NULL,
    PERSONA_RUT NUMBER(8) NOT NULL,
    NIVEL       VARCHAR2(25) NOT NULL
);

ALTER TABLE DOMINIO
    ADD CONSTRAINT DOMINIO_PK
    PRIMARY KEY (ID_IDIOMA, PERSONA_RUT);

ALTER TABLE DOMINIO
    ADD CONSTRAINT DOMINIO_IDIOMA_FK
    FOREIGN KEY (ID_IDIOMA)
    REFERENCES IDIOMA(ID_IDIOMA);

ALTER TABLE DOMINIO
    ADD CONSTRAINT DOMINIO_PERSONAL_FK
    FOREIGN KEY (PERSONA_RUT)
    REFERENCES PERSONAL(RUT_PERSONA);


/* ============================================================
   CASO 2
   MODIFICACION DEL MODELO MEDIANTE ALTER TABLE
   ============================================================ */


/* ------------------------------------------------------------
   El email es opcional, pero no puede repetirse
   ------------------------------------------------------------ */

ALTER TABLE PERSONAL
    ADD CONSTRAINT PERSONAL_EMAIL_UN
    UNIQUE (EMAIL);


/* ------------------------------------------------------------
   Digito verificador permitido
   ------------------------------------------------------------ */

ALTER TABLE PERSONAL
    ADD CONSTRAINT PERSONAL_DV_CK
    CHECK (
        DV_PERSONA IN
        ('0','1','2','3','4','5','6','7','8','9','K')
    );


/* ------------------------------------------------------------
   Sueldo minimo: $450.000
   ------------------------------------------------------------ */

ALTER TABLE PERSONAL
    ADD CONSTRAINT PERSONAL_SUELDO_CK
    CHECK (SUELDO >= 450000);


/* ============================================================
   CASO 3
   POBLAMIENTO DEL MODELO
   ============================================================ */


/* ============================================================
   SECUENCIA PARA COMUNA
   Comienza en 1101 e incrementa de 6 en 6
   ============================================================ */

CREATE SEQUENCE SEQ_COMUNA
    START WITH 1101
    INCREMENT BY 6
    NOCYCLE;


/* ============================================================
   SECUENCIA PARA COMPANIA
   Comienza en 10 e incrementa de 5 en 5
   ============================================================ */

CREATE SEQUENCE SEQ_COMPANIA
    START WITH 10
    INCREMENT BY 5
    NOCYCLE;


/* ============================================================
   POBLAMIENTO DE IDIOMA
   Identity: 25, 28, 31, 34, 37
   ============================================================ */

INSERT INTO IDIOMA (NOMBRE_IDIOMA)
VALUES ('Ingles');

INSERT INTO IDIOMA (NOMBRE_IDIOMA)
VALUES ('Chino');

INSERT INTO IDIOMA (NOMBRE_IDIOMA)
VALUES ('Aleman');

INSERT INTO IDIOMA (NOMBRE_IDIOMA)
VALUES ('Espanol');

INSERT INTO IDIOMA (NOMBRE_IDIOMA)
VALUES ('Frances');


/* ============================================================
   POBLAMIENTO DE REGION
   Identity: 7, 9, 11
   ============================================================ */

INSERT INTO REGION (NOMBRE_REGION)
VALUES ('ARICA Y PARINACOTA');

INSERT INTO REGION (NOMBRE_REGION)
VALUES ('METROPOLITANA');

INSERT INTO REGION (NOMBRE_REGION)
VALUES ('LA ARAUCANIA');


/* ============================================================
   POBLAMIENTO DE COMUNA
   Sequence: 1101, 1107, 1113
   ============================================================ */

INSERT INTO COMUNA (
    ID_COMUNA,
    COMUNA_NOMBRE,
    COD_REGION
)
VALUES (
    SEQ_COMUNA.NEXTVAL,
    'Arica',
    7
);

INSERT INTO COMUNA (
    ID_COMUNA,
    COMUNA_NOMBRE,
    COD_REGION
)
VALUES (
    SEQ_COMUNA.NEXTVAL,
    'Santiago',
    9
);

INSERT INTO COMUNA (
    ID_COMUNA,
    COMUNA_NOMBRE,
    COD_REGION
)
VALUES (
    SEQ_COMUNA.NEXTVAL,
    'Temuco',
    11
);


/* ============================================================
   POBLAMIENTO DE COMPANIA
   ============================================================ */


/* 10 - CCyRojas */

INSERT INTO COMPANIA (
    ID_EMPRESA,
    NOMBRE_EMPRESA,
    CALLE,
    NUMERACION,
    RENTA_PROMEDIO,
    PCT_AUMENTO,
    COD_COMUNA,
    COD_REGION
)
VALUES (
    SEQ_COMPANIA.NEXTVAL,
    'CCyRojas',
    'Amapolas',
    506,
    1857000,
    0.5,
    1101,
    7
);


/* 15 - SenTTy */

INSERT INTO COMPANIA (
    ID_EMPRESA,
    NOMBRE_EMPRESA,
    CALLE,
    NUMERACION,
    RENTA_PROMEDIO,
    PCT_AUMENTO,
    COD_COMUNA,
    COD_REGION
)
VALUES (
    SEQ_COMPANIA.NEXTVAL,
    'SenTTy',
    'Los Alamos',
    3490,
    897000,
    0.025,
    1101,
    7
);


/* 20 - Praxia LTDA */

INSERT INTO COMPANIA (
    ID_EMPRESA,
    NOMBRE_EMPRESA,
    CALLE,
    NUMERACION,
    RENTA_PROMEDIO,
    PCT_AUMENTO,
    COD_COMUNA,
    COD_REGION
)
VALUES (
    SEQ_COMPANIA.NEXTVAL,
    'Praxia LTDA',
    'Las Camelias',
    11098,
    2157000,
    0.035,
    1107,
    9
);


/* 25 - TIC spa */

INSERT INTO COMPANIA (
    ID_EMPRESA,
    NOMBRE_EMPRESA,
    CALLE,
    NUMERACION,
    RENTA_PROMEDIO,
    PCT_AUMENTO,
    COD_COMUNA,
    COD_REGION
)
VALUES (
    SEQ_COMPANIA.NEXTVAL,
    'TIC spa',
    'FLORES S.A.',
    4357,
    857000,
    NULL,
    1107,
    9
);


/* 30 - SANTANA LTDA */

INSERT INTO COMPANIA (
    ID_EMPRESA,
    NOMBRE_EMPRESA,
    CALLE,
    NUMERACION,
    RENTA_PROMEDIO,
    PCT_AUMENTO,
    COD_COMUNA,
    COD_REGION
)
VALUES (
    SEQ_COMPANIA.NEXTVAL,
    'SANTANA LTDA',
    'AVDA VIC. MACKENA',
    106,
    757000,
    0.015,
    1101,
    7
);


/* 35 - FLORES Y ASOCIADOS */

INSERT INTO COMPANIA (
    ID_EMPRESA,
    NOMBRE_EMPRESA,
    CALLE,
    NUMERACION,
    RENTA_PROMEDIO,
    PCT_AUMENTO,
    COD_COMUNA,
    COD_REGION
)
VALUES (
    SEQ_COMPANIA.NEXTVAL,
    'FLORES Y ASOCIADOS',
    'PEDRO LATORRE',
    557,
    589000,
    0.015,
    1107,
    9
);


/* 40 - J.A. HOFFMAN */

INSERT INTO COMPANIA (
    ID_EMPRESA,
    NOMBRE_EMPRESA,
    CALLE,
    NUMERACION,
    RENTA_PROMEDIO,
    PCT_AUMENTO,
    COD_COMUNA,
    COD_REGION
)
VALUES (
    SEQ_COMPANIA.NEXTVAL,
    'J.A. HOFFMAN',
    'LATINA D.32',
    509,
    1857000,
    0.025,
    1113,
    11
);


/* 45 - CAGLIARI D. */

INSERT INTO COMPANIA (
    ID_EMPRESA,
    NOMBRE_EMPRESA,
    CALLE,
    NUMERACION,
    RENTA_PROMEDIO,
    PCT_AUMENTO,
    COD_COMUNA,
    COD_REGION
)
VALUES (
    SEQ_COMPANIA.NEXTVAL,
    'CAGLIARI D.',
    'ALAMEDA',
    206,
    1857000,
    NULL,
    1107,
    9
);


/* 50 - Rojas HNOS LTDA */

INSERT INTO COMPANIA (
    ID_EMPRESA,
    NOMBRE_EMPRESA,
    CALLE,
    NUMERACION,
    RENTA_PROMEDIO,
    PCT_AUMENTO,
    COD_COMUNA,
    COD_REGION
)
VALUES (
    SEQ_COMPANIA.NEXTVAL,
    'Rojas HNOS LTDA',
    'SUCRE',
    106,
    957000,
    0.005,
    1113,
    11
);


/* 55 - FRIENDS P. S.A */

INSERT INTO COMPANIA (
    ID_EMPRESA,
    NOMBRE_EMPRESA,
    CALLE,
    NUMERACION,
    RENTA_PROMEDIO,
    PCT_AUMENTO,
    COD_COMUNA,
    COD_REGION
)
VALUES (
    SEQ_COMPANIA.NEXTVAL,
    'FRIENDS P. S.A',
    'SUECIA',
    506,
    857000,
    0.015,
    1113,
    11
);

COMMIT;


/* ============================================================
   CASO 4
   RECUPERACION DE DATOS
   ============================================================ */


/* ============================================================
   INFORME 1
   Simulacion de Renta Promedio

   Orden:
   1. Renta Promedio DESC
   2. Nombre Empresa ASC
   ============================================================ */

SELECT
    NOMBRE_EMPRESA
        AS "Nombre Empresa",

    CALLE || ' ' || NUMERACION
        AS "Dirección",

    RENTA_PROMEDIO
        AS "Renta Promedio",

    RENTA_PROMEDIO * (1 + PCT_AUMENTO)
        AS "Simulación de Renta"

FROM COMPANIA

ORDER BY
    RENTA_PROMEDIO DESC,
    NOMBRE_EMPRESA ASC;


/* ============================================================
   INFORME 2
   Nueva simulacion de renta promedio

   Se agrega un 15% al porcentaje existente.

   Orden:
   1. Renta promedio actual ASC
   2. Nombre empresa DESC
   ============================================================ */

SELECT
    ID_EMPRESA
        AS "CODIGO",

    NOMBRE_EMPRESA
        AS "EMPRESA",

    RENTA_PROMEDIO
        AS "PROM RENTA ACTUAL",

    PCT_AUMENTO + 0.15
        AS "PCT AUMENTADO EN 15%",

    RENTA_PROMEDIO * (PCT_AUMENTO + 0.15)
        AS "RENTA AUMENTADA"

FROM COMPANIA

ORDER BY
    RENTA_PROMEDIO ASC,
    NOMBRE_EMPRESA DESC;


/* ============================================================
   FIN DEL SCRIPT
   SEMANA 7 - MODELAMIENTO DE BASES DE DATOS
   DUOC UC
   ============================================================ */